---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024
  network:
    # Allow access to the Jenkins webui which is useful when troubleshooting
    - - forwarded_port
      - guest: 8080
        host: 9090
        auto_correct: true

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

platforms:
  - name: debian-7.11
  - name: debian-8.7
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.8
  - name: centos-7.3

suites:
  - name: jenkins_job_create
    run_list:
      - jenkins_job::create_freestyle
      - jenkins_job::create_folder
      - jenkins_job::create_pipeline
      - jenkins_job::create_github_org
      - jenkins_job::create_multibranch_pipeline
