property :job_name, String, name_property: true
property :description, String, default: 'Generated by Chef'
property :display_name, String
property :properties, Hash, default: {}
property :scm, Hash, default: {}, callbacks: { 'scm can only contain one key/value' => proc { |v| v.length <= 1 } }
property :script, String, default: "node { echo 'hello world'}"
property :sandbox, [true, false], default: false
property :template, String, default: 'pipeline-config.xml.erb'
property :cookbook, String, default: 'chef_jenkins'
property :partial_template_cookbook, String
property :auto_create_folders, [true, false], default: true

action :create do
  folder_name = ::File.dirname(new_resource.job_name)
  if new_resource.auto_create_folders && !folder_name.eql?('.')
    folder_name = ::File.dirname(new_resource.job_name)
    chef_jenkins_folder folder_name
  end

  xml = "#{Chef::Config[:file_cache_path]}/#{new_resource.job_name}.xml"

  directory ::File.dirname(xml) do
    recursive true
  end

  partial_template_cookbook_name = property_is_set?(:partial_template_cookbook) ? new_resource.partial_template_cookbook : new_resource.cookbook

  declare_resource(:template, xml) do
    source new_resource.template
    variables(
      description: new_resource.description,
      display_name: new_resource.display_name,
      properties: new_resource.properties,
      scm: new_resource.scm,
      script: new_resource.script,
      sandbox: new_resource.sandbox,
      partial_template_cookbook: partial_template_cookbook_name
    )
    helpers(ChefJenkins::Helper)
    cookbook new_resource.cookbook
  end

  jenkins_job new_resource.job_name do
    config xml
  end
end

action :delete do
  jenkins_job new_resource.job_name do
    action :delete
  end
end

action_class.class_eval do
  include ChefJenkins::Helper
end
